/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actual Numbers</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getActualNumbers()
 * @model
 * @generated
 */
public interface ActualNumbers extends AtomicNumber
{
} // ActualNumbers
