/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AEffect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.AEffect#getAfterEName <em>After EName</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getAEffect()
 * @model
 * @generated
 */
public interface AEffect extends EObject
{
  /**
   * Returns the value of the '<em><b>After EName</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>After EName</em>' reference.
   * @see #setAfterEName(AfterE)
   * @see smitey.rpgindividual.RpgindividualPackage#getAEffect_AfterEName()
   * @model
   * @generated
   */
  AfterE getAfterEName();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.AEffect#getAfterEName <em>After EName</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>After EName</em>' reference.
   * @see #getAfterEName()
   * @generated
   */
  void setAfterEName(AfterE value);

} // AEffect
