/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alt Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.AltAttribute#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link smitey.rpgindividual.AltAttribute#getAv <em>Av</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getAltAttribute()
 * @model
 * @generated
 */
public interface AltAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see smitey.rpgindividual.RpgindividualPackage#getAltAttribute_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.AltAttribute#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Av</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Av</em>' containment reference.
   * @see #setAv(AttributeValues)
   * @see smitey.rpgindividual.RpgindividualPackage#getAltAttribute_Av()
   * @model containment="true"
   * @generated
   */
  AttributeValues getAv();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.AltAttribute#getAv <em>Av</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Av</em>' containment reference.
   * @see #getAv()
   * @generated
   */
  void setAv(AttributeValues value);

} // AltAttribute
