/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getAtomicNumber()
 * @model
 * @generated
 */
public interface AtomicNumber extends Multiply
{
} // AtomicNumber
