/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BEffect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.BEffect#getBuffEName <em>Buff EName</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getBEffect()
 * @model
 * @generated
 */
public interface BEffect extends EObject
{
  /**
   * Returns the value of the '<em><b>Buff EName</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buff EName</em>' reference.
   * @see #setBuffEName(Buff)
   * @see smitey.rpgindividual.RpgindividualPackage#getBEffect_BuffEName()
   * @model
   * @generated
   */
  Buff getBuffEName();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.BEffect#getBuffEName <em>Buff EName</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Buff EName</em>' reference.
   * @see #getBuffEName()
   * @generated
   */
  void setBuffEName(Buff value);

} // BEffect
