/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bigger</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getBigger()
 * @model
 * @generated
 */
public interface Bigger extends Comparator
{
} // Bigger
