/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Death</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.Death#getReq <em>Req</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getDeath()
 * @model
 * @generated
 */
public interface Death extends Declaration
{
  /**
   * Returns the value of the '<em><b>Req</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req</em>' containment reference.
   * @see #setReq(Require)
   * @see smitey.rpgindividual.RpgindividualPackage#getDeath_Req()
   * @model containment="true"
   * @generated
   */
  Require getReq();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.Death#getReq <em>Req</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Req</em>' containment reference.
   * @see #getReq()
   * @generated
   */
  void setReq(Require value);

} // Death
