/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Death</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.Death#getLog <em>Log</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getDeath()
 * @model
 * @generated
 */
public interface Death extends Declaration
{
  /**
   * Returns the value of the '<em><b>Log</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Log</em>' containment reference.
   * @see #setLog(Proposition)
   * @see smitey.rpgindividual.RpgindividualPackage#getDeath_Log()
   * @model containment="true"
   * @generated
   */
  Proposition getLog();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.Death#getLog <em>Log</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Log</em>' containment reference.
   * @see #getLog()
   * @generated
   */
  void setLog(Proposition value);

} // Death
