/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.Entity#getName <em>Name</em>}</li>
 *   <li>{@link smitey.rpgindividual.Entity#getEType <em>EType</em>}</li>
 *   <li>{@link smitey.rpgindividual.Entity#getAtt <em>Att</em>}</li>
 *   <li>{@link smitey.rpgindividual.Entity#getEMoves <em>EMoves</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getEntity()
 * @model
 * @generated
 */
public interface Entity extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see smitey.rpgindividual.RpgindividualPackage#getEntity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.Entity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>EType</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>EType</em>' containment reference.
   * @see #setEType(EType)
   * @see smitey.rpgindividual.RpgindividualPackage#getEntity_EType()
   * @model containment="true"
   * @generated
   */
  EType getEType();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.Entity#getEType <em>EType</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>EType</em>' containment reference.
   * @see #getEType()
   * @generated
   */
  void setEType(EType value);

  /**
   * Returns the value of the '<em><b>Att</b></em>' containment reference list.
   * The list contents are of type {@link smitey.rpgindividual.AltAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Att</em>' containment reference list.
   * @see smitey.rpgindividual.RpgindividualPackage#getEntity_Att()
   * @model containment="true"
   * @generated
   */
  EList<AltAttribute> getAtt();

  /**
   * Returns the value of the '<em><b>EMoves</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>EMoves</em>' containment reference.
   * @see #setEMoves(EntityMoves)
   * @see smitey.rpgindividual.RpgindividualPackage#getEntity_EMoves()
   * @model containment="true"
   * @generated
   */
  EntityMoves getEMoves();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.Entity#getEMoves <em>EMoves</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>EMoves</em>' containment reference.
   * @see #getEMoves()
   * @generated
   */
  void setEMoves(EntityMoves value);

} // Entity
