/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Moves</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.EntityMoves#getMove <em>Move</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoves()
 * @model
 * @generated
 */
public interface EntityMoves extends EObject
{
  /**
   * Returns the value of the '<em><b>Move</b></em>' containment reference list.
   * The list contents are of type {@link smitey.rpgindividual.EntityMoveModifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move</em>' containment reference list.
   * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoves_Move()
   * @model containment="true"
   * @generated
   */
  EList<EntityMoveModifier> getMove();

} // EntityMoves
