/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Num</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.IntNum#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getIntNum()
 * @model
 * @generated
 */
public interface IntNum extends ActualNumbers
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see smitey.rpgindividual.RpgindividualPackage#getIntNum_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.IntNum#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // IntNum
