/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MEffect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.MEffect#getMoveEName <em>Move EName</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getMEffect()
 * @model
 * @generated
 */
public interface MEffect extends EObject
{
  /**
   * Returns the value of the '<em><b>Move EName</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move EName</em>' reference.
   * @see #setMoveEName(Effect)
   * @see smitey.rpgindividual.RpgindividualPackage#getMEffect_MoveEName()
   * @model
   * @generated
   */
  Effect getMoveEName();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.MEffect#getMoveEName <em>Move EName</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Move EName</em>' reference.
   * @see #getMoveEName()
   * @generated
   */
  void setMoveEName(Effect value);

} // MEffect
