/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiply</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getMultiply()
 * @model
 * @generated
 */
public interface Multiply extends Sum
{
} // Multiply
