/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NEq</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getNEq()
 * @model
 * @generated
 */
public interface NEq extends Comparator
{
} // NEq
