/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.Relations#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getRelations()
 * @model
 * @generated
 */
public interface Relations extends Declaration
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference list.
   * The list contents are of type {@link smitey.rpgindividual.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference list.
   * @see smitey.rpgindividual.RpgindividualPackage#getRelations_Type()
   * @model containment="true"
   * @generated
   */
  EList<Type> getType();

} // Relations
