/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Smaller Eq</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getSmallerEq()
 * @model
 * @generated
 */
public interface SmallerEq extends Comparator
{
} // SmallerEq
