/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Team</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.Team#getName <em>Name</em>}</li>
 *   <li>{@link smitey.rpgindividual.Team#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getTeam()
 * @model
 * @generated
 */
public interface Team extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see smitey.rpgindividual.RpgindividualPackage#getTeam_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.Team#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference.
   * @see #setMembers(Members)
   * @see smitey.rpgindividual.RpgindividualPackage#getTeam_Members()
   * @model containment="true"
   * @generated
   */
  Members getMembers();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.Team#getMembers <em>Members</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Members</em>' containment reference.
   * @see #getMembers()
   * @generated
   */
  void setMembers(Members value);

} // Team
