/*
 * generated by Xtext 2.21.0
 */
package smitey.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import smitey.RpgindividualRuntimeModule;
import smitey.RpgindividualStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RpgindividualIdeSetup extends RpgindividualStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RpgindividualRuntimeModule(), new RpgindividualIdeModule()));
	}
	
}
