/*
 * generated by Xtext 2.21.0
 */
package smitey.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RpgindividualGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SystemRPGElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.SystemRPG");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDeclarationsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDeclarationsDeclarationParserRuleCall_2_0 = (RuleCall)cDeclarationsAssignment_2.eContents().get(0);
		
		//SystemRPG:
		//	'game' name=ID declarations+=Declaration*;
		@Override public ParserRule getRule() { return rule; }
		
		//'game' name=ID declarations+=Declaration*
		public Group getGroup() { return cGroup; }
		
		//'game'
		public Keyword getGameKeyword_0() { return cGameKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//declarations+=Declaration*
		public Assignment getDeclarationsAssignment_2() { return cDeclarationsAssignment_2; }
		
		//Declaration
		public RuleCall getDeclarationsDeclarationParserRuleCall_2_0() { return cDeclarationsDeclarationParserRuleCall_2_0; }
	}
	public class DeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Declaration");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLocationsParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRelationsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMovesParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cEntitiesParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cTeamsParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cDeathParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cAttributesParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cEffectsParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Declaration:
		//	Locations | Relations | Moves | Entities | Teams | Death | Attributes | Effects;
		@Override public ParserRule getRule() { return rule; }
		
		//Locations | Relations | Moves | Entities | Teams | Death | Attributes | Effects
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Locations
		public RuleCall getLocationsParserRuleCall_0() { return cLocationsParserRuleCall_0; }
		
		//Relations
		public RuleCall getRelationsParserRuleCall_1() { return cRelationsParserRuleCall_1; }
		
		//Moves
		public RuleCall getMovesParserRuleCall_2() { return cMovesParserRuleCall_2; }
		
		//Entities
		public RuleCall getEntitiesParserRuleCall_3() { return cEntitiesParserRuleCall_3; }
		
		//Teams
		public RuleCall getTeamsParserRuleCall_4() { return cTeamsParserRuleCall_4; }
		
		//Death
		public RuleCall getDeathParserRuleCall_5() { return cDeathParserRuleCall_5; }
		
		//Attributes
		public RuleCall getAttributesParserRuleCall_6() { return cAttributesParserRuleCall_6; }
		
		//Effects
		public RuleCall getEffectsParserRuleCall_7() { return cEffectsParserRuleCall_7; }
	}
	public class EffectsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Effects");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEffectAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEffectEffectParserRuleCall_1_0 = (RuleCall)cEffectAssignment_1.eContents().get(0);
		
		//Effects:
		//	'effects' effect+=Effect+;
		@Override public ParserRule getRule() { return rule; }
		
		//'effects' effect+=Effect+
		public Group getGroup() { return cGroup; }
		
		//'effects'
		public Keyword getEffectsKeyword_0() { return cEffectsKeyword_0; }
		
		//effect+=Effect+
		public Assignment getEffectAssignment_1() { return cEffectAssignment_1; }
		
		//Effect
		public RuleCall getEffectEffectParserRuleCall_1_0() { return cEffectEffectParserRuleCall_1_0; }
	}
	public class EffectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Effect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cMoveEParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Effect:
		//	'effect' MoveE;
		@Override public ParserRule getRule() { return rule; }
		
		//'effect' MoveE
		public Group getGroup() { return cGroup; }
		
		//'effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//MoveE
		public RuleCall getMoveEParserRuleCall_1() { return cMoveEParserRuleCall_1; }
	}
	public class MoveEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.MoveE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMoveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cRuleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRuleRuleParserRuleCall_2_0 = (RuleCall)cRuleAssignment_2.eContents().get(0);
		
		//MoveE:
		//	'move' name=ID rule=Rule;
		@Override public ParserRule getRule() { return rule; }
		
		//'move' name=ID rule=Rule
		public Group getGroup() { return cGroup; }
		
		//'move'
		public Keyword getMoveKeyword_0() { return cMoveKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//rule=Rule
		public Assignment getRuleAssignment_2() { return cRuleAssignment_2; }
		
		//Rule
		public RuleCall getRuleRuleParserRuleCall_2_0() { return cRuleRuleParserRuleCall_2_0; }
	}
	public class AttributesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Attributes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttributesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAttributeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAttributeAttributeParserRuleCall_1_0 = (RuleCall)cAttributeAssignment_1.eContents().get(0);
		
		//Attributes:
		//	'attributes' attribute+=Attribute+;
		@Override public ParserRule getRule() { return rule; }
		
		//'attributes' attribute+=Attribute+
		public Group getGroup() { return cGroup; }
		
		//'attributes'
		public Keyword getAttributesKeyword_0() { return cAttributesKeyword_0; }
		
		//attribute+=Attribute+
		public Assignment getAttributeAssignment_1() { return cAttributeAssignment_1; }
		
		//Attribute
		public RuleCall getAttributeAttributeParserRuleCall_1_0() { return cAttributeAttributeParserRuleCall_1_0; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttributeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cAValAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAValAttributeValuesParserRuleCall_2_0 = (RuleCall)cAValAssignment_2.eContents().get(0);
		
		//Attribute:
		//	'attribute' name=ID aVal=AttributeValues;
		@Override public ParserRule getRule() { return rule; }
		
		//'attribute' name=ID aVal=AttributeValues
		public Group getGroup() { return cGroup; }
		
		//'attribute'
		public Keyword getAttributeKeyword_0() { return cAttributeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//aVal=AttributeValues
		public Assignment getAValAssignment_2() { return cAValAssignment_2; }
		
		//AttributeValues
		public RuleCall getAValAttributeValuesParserRuleCall_2_0() { return cAValAttributeValuesParserRuleCall_2_0; }
	}
	public class LocationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Locations");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLocationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLocAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLocLocParserRuleCall_1_0 = (RuleCall)cLocAssignment_1.eContents().get(0);
		
		//Locations:
		//	'location' loc+=Loc+;
		@Override public ParserRule getRule() { return rule; }
		
		//'location' loc+=Loc+
		public Group getGroup() { return cGroup; }
		
		//'location'
		public Keyword getLocationKeyword_0() { return cLocationKeyword_0; }
		
		//loc+=Loc+
		public Assignment getLocAssignment_1() { return cLocAssignment_1; }
		
		//Loc
		public RuleCall getLocLocParserRuleCall_1_0() { return cLocLocParserRuleCall_1_0; }
	}
	public class LocElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Loc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cOpponentsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTeamAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTeamTeamCrossReference_2_0 = (CrossReference)cTeamAssignment_2.eContents().get(0);
		private final RuleCall cTeamTeamIDTerminalRuleCall_2_0_1 = (RuleCall)cTeamTeamCrossReference_2_0.eContents().get(1);
		
		//Loc:
		//	name=ID 'opponents' team=[Team];
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID 'opponents' team=[Team]
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'opponents'
		public Keyword getOpponentsKeyword_1() { return cOpponentsKeyword_1; }
		
		//team=[Team]
		public Assignment getTeamAssignment_2() { return cTeamAssignment_2; }
		
		//[Team]
		public CrossReference getTeamTeamCrossReference_2_0() { return cTeamTeamCrossReference_2_0; }
		
		//ID
		public RuleCall getTeamTeamIDTerminalRuleCall_2_0_1() { return cTeamTeamIDTerminalRuleCall_2_0_1; }
	}
	public class RelationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Relations");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRelationsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		
		//Relations:
		//	'relations' type+=Type+;
		@Override public ParserRule getRule() { return rule; }
		
		//'relations' type+=Type+
		public Group getGroup() { return cGroup; }
		
		//'relations'
		public Keyword getRelationsKeyword_0() { return cRelationsKeyword_0; }
		
		//type+=Type+
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cTExpressionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTExpressionTypeExpressionParserRuleCall_2_0 = (RuleCall)cTExpressionAssignment_2.eContents().get(0);
		
		//Type:
		//	'type' name=ID tExpression=TypeExpression?;
		@Override public ParserRule getRule() { return rule; }
		
		//'type' name=ID tExpression=TypeExpression?
		public Group getGroup() { return cGroup; }
		
		//'type'
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//tExpression=TypeExpression?
		public Assignment getTExpressionAssignment_2() { return cTExpressionAssignment_2; }
		
		//TypeExpression
		public RuleCall getTExpressionTypeExpressionParserRuleCall_2_0() { return cTExpressionTypeExpressionParserRuleCall_2_0; }
	}
	public class TypeExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.TypeExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStrongAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cStrongTypeCrossReference_0_0 = (CrossReference)cStrongAssignment_0.eContents().get(0);
		private final RuleCall cStrongTypeIDTerminalRuleCall_0_0_1 = (RuleCall)cStrongTypeCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cStrong2Assignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cStrong2TypeCrossReference_1_1_0 = (CrossReference)cStrong2Assignment_1_1.eContents().get(0);
		private final RuleCall cStrong2TypeIDTerminalRuleCall_1_1_0_1 = (RuleCall)cStrong2TypeCrossReference_1_1_0.eContents().get(1);
		private final Keyword cLessThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCurrentTAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cCurrentTTypeCrossReference_3_0 = (CrossReference)cCurrentTAssignment_3.eContents().get(0);
		private final RuleCall cCurrentTTypeIDTerminalRuleCall_3_0_1 = (RuleCall)cCurrentTTypeCrossReference_3_0.eContents().get(1);
		private final Keyword cLessThanSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cWeakAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cWeakTypeCrossReference_5_0 = (CrossReference)cWeakAssignment_5.eContents().get(0);
		private final RuleCall cWeakTypeIDTerminalRuleCall_5_0_1 = (RuleCall)cWeakTypeCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWeak2Assignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cWeak2TypeCrossReference_6_1_0 = (CrossReference)cWeak2Assignment_6_1.eContents().get(0);
		private final RuleCall cWeak2TypeIDTerminalRuleCall_6_1_0_1 = (RuleCall)cWeak2TypeCrossReference_6_1_0.eContents().get(1);
		
		//TypeExpression:
		//	strong=[Type] (',' strong2+=[Type])* '<' currentT=[Type] '<' weak=[Type] (',' weak2+=[Type])*;
		@Override public ParserRule getRule() { return rule; }
		
		//strong=[Type] (',' strong2+=[Type])* '<' currentT=[Type] '<' weak=[Type] (',' weak2+=[Type])*
		public Group getGroup() { return cGroup; }
		
		//strong=[Type]
		public Assignment getStrongAssignment_0() { return cStrongAssignment_0; }
		
		//[Type]
		public CrossReference getStrongTypeCrossReference_0_0() { return cStrongTypeCrossReference_0_0; }
		
		//ID
		public RuleCall getStrongTypeIDTerminalRuleCall_0_0_1() { return cStrongTypeIDTerminalRuleCall_0_0_1; }
		
		//(',' strong2+=[Type])*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//strong2+=[Type]
		public Assignment getStrong2Assignment_1_1() { return cStrong2Assignment_1_1; }
		
		//[Type]
		public CrossReference getStrong2TypeCrossReference_1_1_0() { return cStrong2TypeCrossReference_1_1_0; }
		
		//ID
		public RuleCall getStrong2TypeIDTerminalRuleCall_1_1_0_1() { return cStrong2TypeIDTerminalRuleCall_1_1_0_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_2() { return cLessThanSignKeyword_2; }
		
		//currentT=[Type]
		public Assignment getCurrentTAssignment_3() { return cCurrentTAssignment_3; }
		
		//[Type]
		public CrossReference getCurrentTTypeCrossReference_3_0() { return cCurrentTTypeCrossReference_3_0; }
		
		//ID
		public RuleCall getCurrentTTypeIDTerminalRuleCall_3_0_1() { return cCurrentTTypeIDTerminalRuleCall_3_0_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_4() { return cLessThanSignKeyword_4; }
		
		//weak=[Type]
		public Assignment getWeakAssignment_5() { return cWeakAssignment_5; }
		
		//[Type]
		public CrossReference getWeakTypeCrossReference_5_0() { return cWeakTypeCrossReference_5_0; }
		
		//ID
		public RuleCall getWeakTypeIDTerminalRuleCall_5_0_1() { return cWeakTypeIDTerminalRuleCall_5_0_1; }
		
		//(',' weak2+=[Type])*
		public Group getGroup_6() { return cGroup_6; }
		
		//','
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//weak2+=[Type]
		public Assignment getWeak2Assignment_6_1() { return cWeak2Assignment_6_1; }
		
		//[Type]
		public CrossReference getWeak2TypeCrossReference_6_1_0() { return cWeak2TypeCrossReference_6_1_0; }
		
		//ID
		public RuleCall getWeak2TypeIDTerminalRuleCall_6_1_0_1() { return cWeak2TypeIDTerminalRuleCall_6_1_0_1; }
	}
	public class MovesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Moves");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMovesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMoveAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMoveMoveParserRuleCall_1_0 = (RuleCall)cMoveAssignment_1.eContents().get(0);
		
		//Moves:
		//	'moves' move+=Move+;
		@Override public ParserRule getRule() { return rule; }
		
		//'moves' move+=Move+
		public Group getGroup() { return cGroup; }
		
		//'moves'
		public Keyword getMovesKeyword_0() { return cMovesKeyword_0; }
		
		//move+=Move+
		public Assignment getMoveAssignment_1() { return cMoveAssignment_1; }
		
		//Move
		public RuleCall getMoveMoveParserRuleCall_1_0() { return cMoveMoveParserRuleCall_1_0; }
	}
	public class MoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Move");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMoveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cETypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cETypeETypeParserRuleCall_2_0 = (RuleCall)cETypeAssignment_2.eContents().get(0);
		private final Assignment cAttAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttAltAttributeParserRuleCall_3_0 = (RuleCall)cAttAssignment_3.eContents().get(0);
		private final Assignment cMEffectAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMEffectMEffectParserRuleCall_4_0 = (RuleCall)cMEffectAssignment_4.eContents().get(0);
		
		//Move:
		//	'move' name=ID eType=EType att+=AltAttribute* mEffect+=MEffect+;
		@Override public ParserRule getRule() { return rule; }
		
		//'move' name=ID eType=EType att+=AltAttribute* mEffect+=MEffect+
		public Group getGroup() { return cGroup; }
		
		//'move'
		public Keyword getMoveKeyword_0() { return cMoveKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//eType=EType
		public Assignment getETypeAssignment_2() { return cETypeAssignment_2; }
		
		//EType
		public RuleCall getETypeETypeParserRuleCall_2_0() { return cETypeETypeParserRuleCall_2_0; }
		
		//att+=AltAttribute*
		public Assignment getAttAssignment_3() { return cAttAssignment_3; }
		
		//AltAttribute
		public RuleCall getAttAltAttributeParserRuleCall_3_0() { return cAttAltAttributeParserRuleCall_3_0; }
		
		//mEffect+=MEffect+
		public Assignment getMEffectAssignment_4() { return cMEffectAssignment_4; }
		
		//MEffect
		public RuleCall getMEffectMEffectParserRuleCall_4_0() { return cMEffectMEffectParserRuleCall_4_0; }
	}
	public class MEffectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.MEffect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMoveENameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cMoveENameMoveECrossReference_1_0 = (CrossReference)cMoveENameAssignment_1.eContents().get(0);
		private final RuleCall cMoveENameMoveEIDTerminalRuleCall_1_0_1 = (RuleCall)cMoveENameMoveECrossReference_1_0.eContents().get(1);
		
		//MEffect:
		//	'effect' moveEName=[MoveE];
		@Override public ParserRule getRule() { return rule; }
		
		//'effect' moveEName=[MoveE]
		public Group getGroup() { return cGroup; }
		
		//'effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//moveEName=[MoveE]
		public Assignment getMoveENameAssignment_1() { return cMoveENameAssignment_1; }
		
		//[MoveE]
		public CrossReference getMoveENameMoveECrossReference_1_0() { return cMoveENameMoveECrossReference_1_0; }
		
		//ID
		public RuleCall getMoveENameMoveEIDTerminalRuleCall_1_0_1() { return cMoveENameMoveEIDTerminalRuleCall_1_0_1; }
	}
	public class ETypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.EType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTypeTypeCrossReference_1_0 = (CrossReference)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeTypeIDTerminalRuleCall_1_0_1 = (RuleCall)cTypeTypeCrossReference_1_0.eContents().get(1);
		
		//EType:
		//	'type' type=[Type];
		@Override public ParserRule getRule() { return rule; }
		
		//'type' type=[Type]
		public Group getGroup() { return cGroup; }
		
		//'type'
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }
		
		//type=[Type]
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//[Type]
		public CrossReference getTypeTypeCrossReference_1_0() { return cTypeTypeCrossReference_1_0; }
		
		//ID
		public RuleCall getTypeTypeIDTerminalRuleCall_1_0_1() { return cTypeTypeIDTerminalRuleCall_1_0_1; }
	}
	public class AttributeValuesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.AttributeValues");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cLTypesAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cLTypesLegalTypeParserRuleCall_1_0_0 = (RuleCall)cLTypesAssignment_1_0.eContents().get(0);
		private final Assignment cAnAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cAnActualNumbersParserRuleCall_1_1_0 = (RuleCall)cAnAssignment_1_1.eContents().get(0);
		
		//AttributeValues:
		//	'is' (lTypes=LegalType | an=ActualNumbers);
		@Override public ParserRule getRule() { return rule; }
		
		//'is' (lTypes=LegalType | an=ActualNumbers)
		public Group getGroup() { return cGroup; }
		
		//'is'
		public Keyword getIsKeyword_0() { return cIsKeyword_0; }
		
		//(lTypes=LegalType | an=ActualNumbers)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//lTypes=LegalType
		public Assignment getLTypesAssignment_1_0() { return cLTypesAssignment_1_0; }
		
		//LegalType
		public RuleCall getLTypesLegalTypeParserRuleCall_1_0_0() { return cLTypesLegalTypeParserRuleCall_1_0_0; }
		
		//an=ActualNumbers
		public Assignment getAnAssignment_1_1() { return cAnAssignment_1_1; }
		
		//ActualNumbers
		public RuleCall getAnActualNumbersParserRuleCall_1_1_0() { return cAnActualNumbersParserRuleCall_1_1_0; }
	}
	public class AltAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.AltAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAttributeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAttributeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cAttributeAttributeCrossReference_1_0 = (CrossReference)cAttributeAssignment_1.eContents().get(0);
		private final RuleCall cAttributeAttributeIDTerminalRuleCall_1_0_1 = (RuleCall)cAttributeAttributeCrossReference_1_0.eContents().get(1);
		private final Assignment cAvAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAvAttributeValuesParserRuleCall_2_0 = (RuleCall)cAvAssignment_2.eContents().get(0);
		
		//AltAttribute:
		//	'attribute' attribute=[Attribute] av=AttributeValues?;
		@Override public ParserRule getRule() { return rule; }
		
		//'attribute' attribute=[Attribute] av=AttributeValues?
		public Group getGroup() { return cGroup; }
		
		//'attribute'
		public Keyword getAttributeKeyword_0() { return cAttributeKeyword_0; }
		
		//attribute=[Attribute]
		public Assignment getAttributeAssignment_1() { return cAttributeAssignment_1; }
		
		//[Attribute]
		public CrossReference getAttributeAttributeCrossReference_1_0() { return cAttributeAttributeCrossReference_1_0; }
		
		//ID
		public RuleCall getAttributeAttributeIDTerminalRuleCall_1_0_1() { return cAttributeAttributeIDTerminalRuleCall_1_0_1; }
		
		//av=AttributeValues?
		public Assignment getAvAssignment_2() { return cAvAssignment_2; }
		
		//AttributeValues
		public RuleCall getAvAttributeValuesParserRuleCall_2_0() { return cAvAttributeValuesParserRuleCall_2_0; }
	}
	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cIfKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cOrAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cOrORconditionParserRuleCall_0_1_0 = (RuleCall)cOrAssignment_0_1.eContents().get(0);
		private final Keyword cThenKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cTargetThenAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTargetThenTargetParserRuleCall_1_0 = (RuleCall)cTargetThenAssignment_1.eContents().get(0);
		private final Assignment cTargetAttAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTargetAttAttributeCrossReference_2_0 = (CrossReference)cTargetAttAssignment_2.eContents().get(0);
		private final RuleCall cTargetAttAttributeIDTerminalRuleCall_2_0_1 = (RuleCall)cTargetAttAttributeCrossReference_2_0.eContents().get(1);
		private final Keyword cIsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSumAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSumSumParserRuleCall_4_0 = (RuleCall)cSumAssignment_4.eContents().get(0);
		
		//Rule:
		//	('if' or=ORcondition 'then')? targetThen=Target targetAtt=[Attribute] 'is' sum=Sum;
		@Override public ParserRule getRule() { return rule; }
		
		//('if' or=ORcondition 'then')? targetThen=Target targetAtt=[Attribute] 'is' sum=Sum
		public Group getGroup() { return cGroup; }
		
		//('if' or=ORcondition 'then')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'if'
		public Keyword getIfKeyword_0_0() { return cIfKeyword_0_0; }
		
		//or=ORcondition
		public Assignment getOrAssignment_0_1() { return cOrAssignment_0_1; }
		
		//ORcondition
		public RuleCall getOrORconditionParserRuleCall_0_1_0() { return cOrORconditionParserRuleCall_0_1_0; }
		
		//'then'
		public Keyword getThenKeyword_0_2() { return cThenKeyword_0_2; }
		
		//targetThen=Target
		public Assignment getTargetThenAssignment_1() { return cTargetThenAssignment_1; }
		
		//Target
		public RuleCall getTargetThenTargetParserRuleCall_1_0() { return cTargetThenTargetParserRuleCall_1_0; }
		
		//targetAtt=[Attribute]
		public Assignment getTargetAttAssignment_2() { return cTargetAttAssignment_2; }
		
		//[Attribute]
		public CrossReference getTargetAttAttributeCrossReference_2_0() { return cTargetAttAttributeCrossReference_2_0; }
		
		//ID
		public RuleCall getTargetAttAttributeIDTerminalRuleCall_2_0_1() { return cTargetAttAttributeIDTerminalRuleCall_2_0_1; }
		
		//'is'
		public Keyword getIsKeyword_3() { return cIsKeyword_3; }
		
		//sum=Sum
		public Assignment getSumAssignment_4() { return cSumAssignment_4; }
		
		//Sum
		public RuleCall getSumSumParserRuleCall_4_0() { return cSumSumParserRuleCall_4_0; }
	}
	public class EntitiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Entities");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntitiesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEntityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEntityEntityParserRuleCall_1_0 = (RuleCall)cEntityAssignment_1.eContents().get(0);
		
		//Entities:
		//	'entities' entity+=Entity+;
		@Override public ParserRule getRule() { return rule; }
		
		//'entities' entity+=Entity+
		public Group getGroup() { return cGroup; }
		
		//'entities'
		public Keyword getEntitiesKeyword_0() { return cEntitiesKeyword_0; }
		
		//entity+=Entity+
		public Assignment getEntityAssignment_1() { return cEntityAssignment_1; }
		
		//Entity
		public RuleCall getEntityEntityParserRuleCall_1_0() { return cEntityEntityParserRuleCall_1_0; }
	}
	public class DeathElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Death");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDeathKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWhenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLogAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLogORconditionParserRuleCall_2_0 = (RuleCall)cLogAssignment_2.eContents().get(0);
		
		//Death:
		//	'death' 'when' log=ORcondition;
		@Override public ParserRule getRule() { return rule; }
		
		//'death' 'when' log=ORcondition
		public Group getGroup() { return cGroup; }
		
		//'death'
		public Keyword getDeathKeyword_0() { return cDeathKeyword_0; }
		
		//'when'
		public Keyword getWhenKeyword_1() { return cWhenKeyword_1; }
		
		//log=ORcondition
		public Assignment getLogAssignment_2() { return cLogAssignment_2; }
		
		//ORcondition
		public RuleCall getLogORconditionParserRuleCall_2_0() { return cLogORconditionParserRuleCall_2_0; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cETypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cETypeETypeParserRuleCall_2_0 = (RuleCall)cETypeAssignment_2.eContents().get(0);
		private final Assignment cAttAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttAltAttributeParserRuleCall_3_0 = (RuleCall)cAttAssignment_3.eContents().get(0);
		private final Assignment cEMovesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEMovesEntityMovesParserRuleCall_4_0 = (RuleCall)cEMovesAssignment_4.eContents().get(0);
		
		//Entity:
		//	'entity' name=ID eType=EType att+=AltAttribute* eMoves=EntityMoves;
		@Override public ParserRule getRule() { return rule; }
		
		//'entity' name=ID eType=EType att+=AltAttribute* eMoves=EntityMoves
		public Group getGroup() { return cGroup; }
		
		//'entity'
		public Keyword getEntityKeyword_0() { return cEntityKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//eType=EType
		public Assignment getETypeAssignment_2() { return cETypeAssignment_2; }
		
		//EType
		public RuleCall getETypeETypeParserRuleCall_2_0() { return cETypeETypeParserRuleCall_2_0; }
		
		//att+=AltAttribute*
		public Assignment getAttAssignment_3() { return cAttAssignment_3; }
		
		//AltAttribute
		public RuleCall getAttAltAttributeParserRuleCall_3_0() { return cAttAltAttributeParserRuleCall_3_0; }
		
		//eMoves=EntityMoves
		public Assignment getEMovesAssignment_4() { return cEMovesAssignment_4; }
		
		//EntityMoves
		public RuleCall getEMovesEntityMovesParserRuleCall_4_0() { return cEMovesEntityMovesParserRuleCall_4_0; }
	}
	public class EntityMovesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.EntityMoves");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMoveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMoveAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMoveEntityMoveModifierParserRuleCall_1_0 = (RuleCall)cMoveAssignment_1.eContents().get(0);
		
		//EntityMoves:
		//	'move' move+=EntityMoveModifier+;
		@Override public ParserRule getRule() { return rule; }
		
		//'move' move+=EntityMoveModifier+
		public Group getGroup() { return cGroup; }
		
		//'move'
		public Keyword getMoveKeyword_0() { return cMoveKeyword_0; }
		
		//move+=EntityMoveModifier+
		public Assignment getMoveAssignment_1() { return cMoveAssignment_1; }
		
		//EntityMoveModifier
		public RuleCall getMoveEntityMoveModifierParserRuleCall_1_0() { return cMoveEntityMoveModifierParserRuleCall_1_0; }
	}
	public class EntityMoveModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.EntityMoveModifier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMoveNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cMoveNameMoveCrossReference_0_0 = (CrossReference)cMoveNameAssignment_0.eContents().get(0);
		private final RuleCall cMoveNameMoveIDTerminalRuleCall_0_0_1 = (RuleCall)cMoveNameMoveCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMoveModificationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMoveModificationEntityMoveMultiplierParserRuleCall_2_0 = (RuleCall)cMoveModificationAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//EntityMoveModifier:
		//	moveName=[Move] '(' moveModification+=EntityMoveMultiplier* ')';
		@Override public ParserRule getRule() { return rule; }
		
		//moveName=[Move] '(' moveModification+=EntityMoveMultiplier* ')'
		public Group getGroup() { return cGroup; }
		
		//moveName=[Move]
		public Assignment getMoveNameAssignment_0() { return cMoveNameAssignment_0; }
		
		//[Move]
		public CrossReference getMoveNameMoveCrossReference_0_0() { return cMoveNameMoveCrossReference_0_0; }
		
		//ID
		public RuleCall getMoveNameMoveIDTerminalRuleCall_0_0_1() { return cMoveNameMoveIDTerminalRuleCall_0_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//moveModification+=EntityMoveMultiplier*
		public Assignment getMoveModificationAssignment_2() { return cMoveModificationAssignment_2; }
		
		//EntityMoveMultiplier
		public RuleCall getMoveModificationEntityMoveMultiplierParserRuleCall_2_0() { return cMoveModificationEntityMoveMultiplierParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class EntityMoveMultiplierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.EntityMoveMultiplier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAttributeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cAttributeAttributeCrossReference_0_0 = (CrossReference)cAttributeAssignment_0.eContents().get(0);
		private final RuleCall cAttributeAttributeIDTerminalRuleCall_0_0_1 = (RuleCall)cAttributeAttributeCrossReference_0_0.eContents().get(1);
		private final Keyword cAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMultiplierAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMultiplierSumParserRuleCall_2_0 = (RuleCall)cMultiplierAssignment_2.eContents().get(0);
		
		//EntityMoveMultiplier:
		//	attribute=[Attribute] "*" multiplier=Sum;
		@Override public ParserRule getRule() { return rule; }
		
		//attribute=[Attribute] "*" multiplier=Sum
		public Group getGroup() { return cGroup; }
		
		//attribute=[Attribute]
		public Assignment getAttributeAssignment_0() { return cAttributeAssignment_0; }
		
		//[Attribute]
		public CrossReference getAttributeAttributeCrossReference_0_0() { return cAttributeAttributeCrossReference_0_0; }
		
		//ID
		public RuleCall getAttributeAttributeIDTerminalRuleCall_0_0_1() { return cAttributeAttributeIDTerminalRuleCall_0_0_1; }
		
		//"*"
		public Keyword getAsteriskKeyword_1() { return cAsteriskKeyword_1; }
		
		//multiplier=Sum
		public Assignment getMultiplierAssignment_2() { return cMultiplierAssignment_2; }
		
		//Sum
		public RuleCall getMultiplierSumParserRuleCall_2_0() { return cMultiplierSumParserRuleCall_2_0; }
	}
	public class TeamsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Teams");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTeamsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTeamAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTeamTeamParserRuleCall_1_0 = (RuleCall)cTeamAssignment_1.eContents().get(0);
		
		//Teams:
		//	'teams' team+=Team+;
		@Override public ParserRule getRule() { return rule; }
		
		//'teams' team+=Team+
		public Group getGroup() { return cGroup; }
		
		//'teams'
		public Keyword getTeamsKeyword_0() { return cTeamsKeyword_0; }
		
		//team+=Team+
		public Assignment getTeamAssignment_1() { return cTeamAssignment_1; }
		
		//Team
		public RuleCall getTeamTeamParserRuleCall_1_0() { return cTeamTeamParserRuleCall_1_0; }
	}
	public class TeamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Team");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTeamKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cMembersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMembersMembersParserRuleCall_2_0 = (RuleCall)cMembersAssignment_2.eContents().get(0);
		
		//Team:
		//	'team' name=ID members=Members;
		@Override public ParserRule getRule() { return rule; }
		
		//'team' name=ID members=Members
		public Group getGroup() { return cGroup; }
		
		//'team'
		public Keyword getTeamKeyword_0() { return cTeamKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//members=Members
		public Assignment getMembersAssignment_2() { return cMembersAssignment_2; }
		
		//Members
		public RuleCall getMembersMembersParserRuleCall_2_0() { return cMembersMembersParserRuleCall_2_0; }
	}
	public class MembersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Members");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMembersKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEntityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEntityEntityCrossReference_1_0 = (CrossReference)cEntityAssignment_1.eContents().get(0);
		private final RuleCall cEntityEntityIDTerminalRuleCall_1_0_1 = (RuleCall)cEntityEntityCrossReference_1_0.eContents().get(1);
		
		//Members:
		//	'members' entity+=[Entity]+;
		@Override public ParserRule getRule() { return rule; }
		
		//'members' entity+=[Entity]+
		public Group getGroup() { return cGroup; }
		
		//'members'
		public Keyword getMembersKeyword_0() { return cMembersKeyword_0; }
		
		//entity+=[Entity]+
		public Assignment getEntityAssignment_1() { return cEntityAssignment_1; }
		
		//[Entity]
		public CrossReference getEntityEntityCrossReference_1_0() { return cEntityEntityCrossReference_1_0; }
		
		//ID
		public RuleCall getEntityEntityIDTerminalRuleCall_1_0_1() { return cEntityEntityIDTerminalRuleCall_1_0_1; }
	}
	public class ORconditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.ORcondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cANDconditionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cORKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cOrLeftAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightANDconditionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ORcondition Proposition:
		//	ANDcondition ('OR' {Or.left=current} right=ANDcondition)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ANDcondition ('OR' {Or.left=current} right=ANDcondition)*
		public Group getGroup() { return cGroup; }
		
		//ANDcondition
		public RuleCall getANDconditionParserRuleCall_0() { return cANDconditionParserRuleCall_0; }
		
		//('OR' {Or.left=current} right=ANDcondition)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'OR'
		public Keyword getORKeyword_1_0() { return cORKeyword_1_0; }
		
		//{Or.left=current}
		public Action getOrLeftAction_1_1() { return cOrLeftAction_1_1; }
		
		//right=ANDcondition
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//ANDcondition
		public RuleCall getRightANDconditionParserRuleCall_1_2_0() { return cRightANDconditionParserRuleCall_1_2_0; }
	}
	public class ANDconditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.ANDcondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cStatementParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cANDKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cAndLeftAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightStatementParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ANDcondition Proposition:
		//	Statement ('AND' {And.left=current} right=Statement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Statement ('AND' {And.left=current} right=Statement)*
		public Group getGroup() { return cGroup; }
		
		//Statement
		public RuleCall getStatementParserRuleCall_0() { return cStatementParserRuleCall_0; }
		
		//('AND' {And.left=current} right=Statement)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'AND'
		public Keyword getANDKeyword_1_0() { return cANDKeyword_1_0; }
		
		//{And.left=current}
		public Action getAndLeftAction_1_1() { return cAndLeftAction_1_1; }
		
		//right=Statement
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Statement
		public RuleCall getRightStatementParserRuleCall_1_2_0() { return cRightStatementParserRuleCall_1_2_0; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNumberComparingParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cORconditionParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Statement Proposition:
		//	NumberComparing | '(' ORcondition ')';
		@Override public ParserRule getRule() { return rule; }
		
		//NumberComparing | '(' ORcondition ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NumberComparing
		public RuleCall getNumberComparingParserRuleCall_0() { return cNumberComparingParserRuleCall_0; }
		
		//'(' ORcondition ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//ORcondition
		public RuleCall getORconditionParserRuleCall_1_1() { return cORconditionParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class NumberComparingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.NumberComparing");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftSumParserRuleCall_0_0 = (RuleCall)cLeftAssignment_0.eContents().get(0);
		private final Assignment cCompAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCompComparatorParserRuleCall_1_0 = (RuleCall)cCompAssignment_1.eContents().get(0);
		private final Assignment cRightAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRightSumParserRuleCall_2_0 = (RuleCall)cRightAssignment_2.eContents().get(0);
		
		//NumberComparing:
		//	left=Sum comp=Comparator right=Sum;
		@Override public ParserRule getRule() { return rule; }
		
		//left=Sum comp=Comparator right=Sum
		public Group getGroup() { return cGroup; }
		
		//left=Sum
		public Assignment getLeftAssignment_0() { return cLeftAssignment_0; }
		
		//Sum
		public RuleCall getLeftSumParserRuleCall_0_0() { return cLeftSumParserRuleCall_0_0; }
		
		//comp=Comparator
		public Assignment getCompAssignment_1() { return cCompAssignment_1; }
		
		//Comparator
		public RuleCall getCompComparatorParserRuleCall_1_0() { return cCompComparatorParserRuleCall_1_0; }
		
		//right=Sum
		public Assignment getRightAssignment_2() { return cRightAssignment_2; }
		
		//Sum
		public RuleCall getRightSumParserRuleCall_2_0() { return cRightSumParserRuleCall_2_0; }
	}
	public class ComparatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Comparator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cSmallerAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cLessThanSignKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cSmallerEqAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cLessThanSignEqualsSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cEqAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cEqualsSignEqualsSignKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cBiggerEqAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cGreaterThanSignEqualsSignKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cBiggerAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cNEqAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cExclamationMarkEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		
		//Comparator:
		//	{Smaller} '<' | {SmallerEq} '<=' | {Eq} '==' | {BiggerEq} '>=' | {Bigger} '>' | {NEq} '!=';
		@Override public ParserRule getRule() { return rule; }
		
		//{Smaller} '<' | {SmallerEq} '<=' | {Eq} '==' | {BiggerEq} '>=' | {Bigger} '>' | {NEq} '!='
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Smaller} '<'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Smaller}
		public Action getSmallerAction_0_0() { return cSmallerAction_0_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_0_1() { return cLessThanSignKeyword_0_1; }
		
		//{SmallerEq} '<='
		public Group getGroup_1() { return cGroup_1; }
		
		//{SmallerEq}
		public Action getSmallerEqAction_1_0() { return cSmallerEqAction_1_0; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_1_1() { return cLessThanSignEqualsSignKeyword_1_1; }
		
		//{Eq} '=='
		public Group getGroup_2() { return cGroup_2; }
		
		//{Eq}
		public Action getEqAction_2_0() { return cEqAction_2_0; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_2_1() { return cEqualsSignEqualsSignKeyword_2_1; }
		
		//{BiggerEq} '>='
		public Group getGroup_3() { return cGroup_3; }
		
		//{BiggerEq}
		public Action getBiggerEqAction_3_0() { return cBiggerEqAction_3_0; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_3_1() { return cGreaterThanSignEqualsSignKeyword_3_1; }
		
		//{Bigger} '>'
		public Group getGroup_4() { return cGroup_4; }
		
		//{Bigger}
		public Action getBiggerAction_4_0() { return cBiggerAction_4_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_4_1() { return cGreaterThanSignKeyword_4_1; }
		
		//{NEq} '!='
		public Group getGroup_5() { return cGroup_5; }
		
		//{NEq}
		public Action getNEqAction_5_0() { return cNEqAction_5_0; }
		
		//'!='
		public Keyword getExclamationMarkEqualsSignKeyword_5_1() { return cExclamationMarkEqualsSignKeyword_5_1; }
	}
	public class SumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Sum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplyParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_0_0_0 = (Keyword)cGroup_1_0_0.eContents().get(0);
		private final Action cAddLeftAction_1_0_0_1 = (Action)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_1_0_1_0 = (Keyword)cGroup_1_0_1.eContents().get(0);
		private final Action cSubLeftAction_1_0_1_1 = (Action)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightMultiplyParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Sum:
		//	Multiply (('+' {Add.left=current} | '-' {Sub.left=current}) right=Multiply)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Multiply (('+' {Add.left=current} | '-' {Sub.left=current}) right=Multiply)*
		public Group getGroup() { return cGroup; }
		
		//Multiply
		public RuleCall getMultiplyParserRuleCall_0() { return cMultiplyParserRuleCall_0; }
		
		//(('+' {Add.left=current} | '-' {Sub.left=current}) right=Multiply)*
		public Group getGroup_1() { return cGroup_1; }
		
		//('+' {Add.left=current} | '-' {Sub.left=current})
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//'+' {Add.left=current}
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1_0_0_0() { return cPlusSignKeyword_1_0_0_0; }
		
		//{Add.left=current}
		public Action getAddLeftAction_1_0_0_1() { return cAddLeftAction_1_0_0_1; }
		
		//'-' {Sub.left=current}
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_0_1_0() { return cHyphenMinusKeyword_1_0_1_0; }
		
		//{Sub.left=current}
		public Action getSubLeftAction_1_0_1_1() { return cSubLeftAction_1_0_1_1; }
		
		//right=Multiply
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Multiply
		public RuleCall getRightMultiplyParserRuleCall_1_1_0() { return cRightMultiplyParserRuleCall_1_1_0; }
	}
	public class MultiplyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Multiply");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAtomicNumberParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_0_0_0 = (Keyword)cGroup_1_0_0.eContents().get(0);
		private final Action cMultLeftAction_1_0_0_1 = (Action)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Keyword cSolidusKeyword_1_0_1_0 = (Keyword)cGroup_1_0_1.eContents().get(0);
		private final Action cDivLeftAction_1_0_1_1 = (Action)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightAtomicNumberParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Multiply:
		//	AtomicNumber (('*' {Mult.left=current} | '/' {Div.left=current}) right=AtomicNumber)*;
		@Override public ParserRule getRule() { return rule; }
		
		//AtomicNumber (('*' {Mult.left=current} | '/' {Div.left=current}) right=AtomicNumber)*
		public Group getGroup() { return cGroup; }
		
		//AtomicNumber
		public RuleCall getAtomicNumberParserRuleCall_0() { return cAtomicNumberParserRuleCall_0; }
		
		//(('*' {Mult.left=current} | '/' {Div.left=current}) right=AtomicNumber)*
		public Group getGroup_1() { return cGroup_1; }
		
		//('*' {Mult.left=current} | '/' {Div.left=current})
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//'*' {Mult.left=current}
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_1_0_0_0() { return cAsteriskKeyword_1_0_0_0; }
		
		//{Mult.left=current}
		public Action getMultLeftAction_1_0_0_1() { return cMultLeftAction_1_0_0_1; }
		
		//'/' {Div.left=current}
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0_1_0() { return cSolidusKeyword_1_0_1_0; }
		
		//{Div.left=current}
		public Action getDivLeftAction_1_0_1_1() { return cDivLeftAction_1_0_1_1; }
		
		//right=AtomicNumber
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//AtomicNumber
		public RuleCall getRightAtomicNumberParserRuleCall_1_1_0() { return cRightAtomicNumberParserRuleCall_1_1_0; }
	}
	public class AtomicNumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.AtomicNumber");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cActualNumbersParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNameAttributeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AtomicNumber:
		//	ActualNumbers | NameAttribute;
		@Override public ParserRule getRule() { return rule; }
		
		//ActualNumbers | NameAttribute
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ActualNumbers
		public RuleCall getActualNumbersParserRuleCall_0() { return cActualNumbersParserRuleCall_0; }
		
		//NameAttribute
		public RuleCall getNameAttributeParserRuleCall_1() { return cNameAttributeParserRuleCall_1; }
	}
	public class ActualNumbersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.ActualNumbers");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFloatNumParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntNumParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ActualNumbers:
		//	FloatNum | IntNum;
		@Override public ParserRule getRule() { return rule; }
		
		//FloatNum | IntNum
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FloatNum
		public RuleCall getFloatNumParserRuleCall_0() { return cFloatNumParserRuleCall_0; }
		
		//IntNum
		public RuleCall getIntNumParserRuleCall_1() { return cIntNumParserRuleCall_1; }
	}
	public class NameAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.NameAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTargetAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTargetTargetParserRuleCall_0_0 = (RuleCall)cTargetAssignment_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cAttributeAttributeCrossReference_1_0 = (CrossReference)cAttributeAssignment_1.eContents().get(0);
		private final RuleCall cAttributeAttributeIDTerminalRuleCall_1_0_1 = (RuleCall)cAttributeAttributeCrossReference_1_0.eContents().get(1);
		
		//NameAttribute:
		//	target=Target attribute=[Attribute];
		@Override public ParserRule getRule() { return rule; }
		
		//target=Target attribute=[Attribute]
		public Group getGroup() { return cGroup; }
		
		//target=Target
		public Assignment getTargetAssignment_0() { return cTargetAssignment_0; }
		
		//Target
		public RuleCall getTargetTargetParserRuleCall_0_0() { return cTargetTargetParserRuleCall_0_0; }
		
		//attribute=[Attribute]
		public Assignment getAttributeAssignment_1() { return cAttributeAssignment_1; }
		
		//[Attribute]
		public CrossReference getAttributeAttributeCrossReference_1_0() { return cAttributeAttributeCrossReference_1_0; }
		
		//ID
		public RuleCall getAttributeAttributeIDTerminalRuleCall_1_0_1() { return cAttributeAttributeIDTerminalRuleCall_1_0_1; }
	}
	public class IntNumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.IntNum");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntNum:
		//	value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class FloatNumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.FloatNum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIINTTerminalRuleCall_0_0 = (RuleCall)cIAssignment_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDecimalAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDecimalINTTerminalRuleCall_2_0 = (RuleCall)cDecimalAssignment_2.eContents().get(0);
		
		//FloatNum:
		//	i=INT '.' decimal=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//i=INT '.' decimal=INT
		public Group getGroup() { return cGroup; }
		
		//i=INT
		public Assignment getIAssignment_0() { return cIAssignment_0; }
		
		//INT
		public RuleCall getIINTTerminalRuleCall_0_0() { return cIINTTerminalRuleCall_0_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//decimal=INT
		public Assignment getDecimalAssignment_2() { return cDecimalAssignment_2; }
		
		//INT
		public RuleCall getDecimalINTTerminalRuleCall_2_0() { return cDecimalINTTerminalRuleCall_2_0; }
	}
	public class TargetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.Target");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cUserKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cEnemyKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Target:
		//	'User' | 'Enemy';
		@Override public ParserRule getRule() { return rule; }
		
		//'User' | 'Enemy'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'User'
		public Keyword getUserKeyword_0() { return cUserKeyword_0; }
		
		//'Enemy'
		public Keyword getEnemyKeyword_1() { return cEnemyKeyword_1; }
	}
	public class LegalTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "smitey.Rpgindividual.LegalType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cFloatKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cIntegerKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//LegalType:
		//	'Float' | 'Integer';
		@Override public ParserRule getRule() { return rule; }
		
		//'Float' | 'Integer'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'Float'
		public Keyword getFloatKeyword_0() { return cFloatKeyword_0; }
		
		//'Integer'
		public Keyword getIntegerKeyword_1() { return cIntegerKeyword_1; }
	}
	
	
	private final SystemRPGElements pSystemRPG;
	private final DeclarationElements pDeclaration;
	private final EffectsElements pEffects;
	private final EffectElements pEffect;
	private final MoveEElements pMoveE;
	private final AttributesElements pAttributes;
	private final AttributeElements pAttribute;
	private final LocationsElements pLocations;
	private final LocElements pLoc;
	private final RelationsElements pRelations;
	private final TypeElements pType;
	private final TypeExpressionElements pTypeExpression;
	private final MovesElements pMoves;
	private final MoveElements pMove;
	private final MEffectElements pMEffect;
	private final ETypeElements pEType;
	private final AttributeValuesElements pAttributeValues;
	private final AltAttributeElements pAltAttribute;
	private final RuleElements pRule;
	private final EntitiesElements pEntities;
	private final DeathElements pDeath;
	private final EntityElements pEntity;
	private final EntityMovesElements pEntityMoves;
	private final EntityMoveModifierElements pEntityMoveModifier;
	private final EntityMoveMultiplierElements pEntityMoveMultiplier;
	private final TeamsElements pTeams;
	private final TeamElements pTeam;
	private final MembersElements pMembers;
	private final ORconditionElements pORcondition;
	private final ANDconditionElements pANDcondition;
	private final StatementElements pStatement;
	private final NumberComparingElements pNumberComparing;
	private final ComparatorElements pComparator;
	private final SumElements pSum;
	private final MultiplyElements pMultiply;
	private final AtomicNumberElements pAtomicNumber;
	private final ActualNumbersElements pActualNumbers;
	private final NameAttributeElements pNameAttribute;
	private final IntNumElements pIntNum;
	private final FloatNumElements pFloatNum;
	private final TargetElements pTarget;
	private final LegalTypeElements pLegalType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RpgindividualGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSystemRPG = new SystemRPGElements();
		this.pDeclaration = new DeclarationElements();
		this.pEffects = new EffectsElements();
		this.pEffect = new EffectElements();
		this.pMoveE = new MoveEElements();
		this.pAttributes = new AttributesElements();
		this.pAttribute = new AttributeElements();
		this.pLocations = new LocationsElements();
		this.pLoc = new LocElements();
		this.pRelations = new RelationsElements();
		this.pType = new TypeElements();
		this.pTypeExpression = new TypeExpressionElements();
		this.pMoves = new MovesElements();
		this.pMove = new MoveElements();
		this.pMEffect = new MEffectElements();
		this.pEType = new ETypeElements();
		this.pAttributeValues = new AttributeValuesElements();
		this.pAltAttribute = new AltAttributeElements();
		this.pRule = new RuleElements();
		this.pEntities = new EntitiesElements();
		this.pDeath = new DeathElements();
		this.pEntity = new EntityElements();
		this.pEntityMoves = new EntityMovesElements();
		this.pEntityMoveModifier = new EntityMoveModifierElements();
		this.pEntityMoveMultiplier = new EntityMoveMultiplierElements();
		this.pTeams = new TeamsElements();
		this.pTeam = new TeamElements();
		this.pMembers = new MembersElements();
		this.pORcondition = new ORconditionElements();
		this.pANDcondition = new ANDconditionElements();
		this.pStatement = new StatementElements();
		this.pNumberComparing = new NumberComparingElements();
		this.pComparator = new ComparatorElements();
		this.pSum = new SumElements();
		this.pMultiply = new MultiplyElements();
		this.pAtomicNumber = new AtomicNumberElements();
		this.pActualNumbers = new ActualNumbersElements();
		this.pNameAttribute = new NameAttributeElements();
		this.pIntNum = new IntNumElements();
		this.pFloatNum = new FloatNumElements();
		this.pTarget = new TargetElements();
		this.pLegalType = new LegalTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("smitey.Rpgindividual".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SystemRPG:
	//	'game' name=ID declarations+=Declaration*;
	public SystemRPGElements getSystemRPGAccess() {
		return pSystemRPG;
	}
	
	public ParserRule getSystemRPGRule() {
		return getSystemRPGAccess().getRule();
	}
	
	//Declaration:
	//	Locations | Relations | Moves | Entities | Teams | Death | Attributes | Effects;
	public DeclarationElements getDeclarationAccess() {
		return pDeclaration;
	}
	
	public ParserRule getDeclarationRule() {
		return getDeclarationAccess().getRule();
	}
	
	//Effects:
	//	'effects' effect+=Effect+;
	public EffectsElements getEffectsAccess() {
		return pEffects;
	}
	
	public ParserRule getEffectsRule() {
		return getEffectsAccess().getRule();
	}
	
	//Effect:
	//	'effect' MoveE;
	public EffectElements getEffectAccess() {
		return pEffect;
	}
	
	public ParserRule getEffectRule() {
		return getEffectAccess().getRule();
	}
	
	//MoveE:
	//	'move' name=ID rule=Rule;
	public MoveEElements getMoveEAccess() {
		return pMoveE;
	}
	
	public ParserRule getMoveERule() {
		return getMoveEAccess().getRule();
	}
	
	//Attributes:
	//	'attributes' attribute+=Attribute+;
	public AttributesElements getAttributesAccess() {
		return pAttributes;
	}
	
	public ParserRule getAttributesRule() {
		return getAttributesAccess().getRule();
	}
	
	//Attribute:
	//	'attribute' name=ID aVal=AttributeValues;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//Locations:
	//	'location' loc+=Loc+;
	public LocationsElements getLocationsAccess() {
		return pLocations;
	}
	
	public ParserRule getLocationsRule() {
		return getLocationsAccess().getRule();
	}
	
	//Loc:
	//	name=ID 'opponents' team=[Team];
	public LocElements getLocAccess() {
		return pLoc;
	}
	
	public ParserRule getLocRule() {
		return getLocAccess().getRule();
	}
	
	//Relations:
	//	'relations' type+=Type+;
	public RelationsElements getRelationsAccess() {
		return pRelations;
	}
	
	public ParserRule getRelationsRule() {
		return getRelationsAccess().getRule();
	}
	
	//Type:
	//	'type' name=ID tExpression=TypeExpression?;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//TypeExpression:
	//	strong=[Type] (',' strong2+=[Type])* '<' currentT=[Type] '<' weak=[Type] (',' weak2+=[Type])*;
	public TypeExpressionElements getTypeExpressionAccess() {
		return pTypeExpression;
	}
	
	public ParserRule getTypeExpressionRule() {
		return getTypeExpressionAccess().getRule();
	}
	
	//Moves:
	//	'moves' move+=Move+;
	public MovesElements getMovesAccess() {
		return pMoves;
	}
	
	public ParserRule getMovesRule() {
		return getMovesAccess().getRule();
	}
	
	//Move:
	//	'move' name=ID eType=EType att+=AltAttribute* mEffect+=MEffect+;
	public MoveElements getMoveAccess() {
		return pMove;
	}
	
	public ParserRule getMoveRule() {
		return getMoveAccess().getRule();
	}
	
	//MEffect:
	//	'effect' moveEName=[MoveE];
	public MEffectElements getMEffectAccess() {
		return pMEffect;
	}
	
	public ParserRule getMEffectRule() {
		return getMEffectAccess().getRule();
	}
	
	//EType:
	//	'type' type=[Type];
	public ETypeElements getETypeAccess() {
		return pEType;
	}
	
	public ParserRule getETypeRule() {
		return getETypeAccess().getRule();
	}
	
	//AttributeValues:
	//	'is' (lTypes=LegalType | an=ActualNumbers);
	public AttributeValuesElements getAttributeValuesAccess() {
		return pAttributeValues;
	}
	
	public ParserRule getAttributeValuesRule() {
		return getAttributeValuesAccess().getRule();
	}
	
	//AltAttribute:
	//	'attribute' attribute=[Attribute] av=AttributeValues?;
	public AltAttributeElements getAltAttributeAccess() {
		return pAltAttribute;
	}
	
	public ParserRule getAltAttributeRule() {
		return getAltAttributeAccess().getRule();
	}
	
	//Rule:
	//	('if' or=ORcondition 'then')? targetThen=Target targetAtt=[Attribute] 'is' sum=Sum;
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}
	
	//Entities:
	//	'entities' entity+=Entity+;
	public EntitiesElements getEntitiesAccess() {
		return pEntities;
	}
	
	public ParserRule getEntitiesRule() {
		return getEntitiesAccess().getRule();
	}
	
	//Death:
	//	'death' 'when' log=ORcondition;
	public DeathElements getDeathAccess() {
		return pDeath;
	}
	
	public ParserRule getDeathRule() {
		return getDeathAccess().getRule();
	}
	
	//Entity:
	//	'entity' name=ID eType=EType att+=AltAttribute* eMoves=EntityMoves;
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//EntityMoves:
	//	'move' move+=EntityMoveModifier+;
	public EntityMovesElements getEntityMovesAccess() {
		return pEntityMoves;
	}
	
	public ParserRule getEntityMovesRule() {
		return getEntityMovesAccess().getRule();
	}
	
	//EntityMoveModifier:
	//	moveName=[Move] '(' moveModification+=EntityMoveMultiplier* ')';
	public EntityMoveModifierElements getEntityMoveModifierAccess() {
		return pEntityMoveModifier;
	}
	
	public ParserRule getEntityMoveModifierRule() {
		return getEntityMoveModifierAccess().getRule();
	}
	
	//EntityMoveMultiplier:
	//	attribute=[Attribute] "*" multiplier=Sum;
	public EntityMoveMultiplierElements getEntityMoveMultiplierAccess() {
		return pEntityMoveMultiplier;
	}
	
	public ParserRule getEntityMoveMultiplierRule() {
		return getEntityMoveMultiplierAccess().getRule();
	}
	
	//Teams:
	//	'teams' team+=Team+;
	public TeamsElements getTeamsAccess() {
		return pTeams;
	}
	
	public ParserRule getTeamsRule() {
		return getTeamsAccess().getRule();
	}
	
	//Team:
	//	'team' name=ID members=Members;
	public TeamElements getTeamAccess() {
		return pTeam;
	}
	
	public ParserRule getTeamRule() {
		return getTeamAccess().getRule();
	}
	
	//Members:
	//	'members' entity+=[Entity]+;
	public MembersElements getMembersAccess() {
		return pMembers;
	}
	
	public ParserRule getMembersRule() {
		return getMembersAccess().getRule();
	}
	
	//ORcondition Proposition:
	//	ANDcondition ('OR' {Or.left=current} right=ANDcondition)*;
	public ORconditionElements getORconditionAccess() {
		return pORcondition;
	}
	
	public ParserRule getORconditionRule() {
		return getORconditionAccess().getRule();
	}
	
	//ANDcondition Proposition:
	//	Statement ('AND' {And.left=current} right=Statement)*;
	public ANDconditionElements getANDconditionAccess() {
		return pANDcondition;
	}
	
	public ParserRule getANDconditionRule() {
		return getANDconditionAccess().getRule();
	}
	
	//Statement Proposition:
	//	NumberComparing | '(' ORcondition ')';
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//NumberComparing:
	//	left=Sum comp=Comparator right=Sum;
	public NumberComparingElements getNumberComparingAccess() {
		return pNumberComparing;
	}
	
	public ParserRule getNumberComparingRule() {
		return getNumberComparingAccess().getRule();
	}
	
	//Comparator:
	//	{Smaller} '<' | {SmallerEq} '<=' | {Eq} '==' | {BiggerEq} '>=' | {Bigger} '>' | {NEq} '!=';
	public ComparatorElements getComparatorAccess() {
		return pComparator;
	}
	
	public ParserRule getComparatorRule() {
		return getComparatorAccess().getRule();
	}
	
	//Sum:
	//	Multiply (('+' {Add.left=current} | '-' {Sub.left=current}) right=Multiply)*;
	public SumElements getSumAccess() {
		return pSum;
	}
	
	public ParserRule getSumRule() {
		return getSumAccess().getRule();
	}
	
	//Multiply:
	//	AtomicNumber (('*' {Mult.left=current} | '/' {Div.left=current}) right=AtomicNumber)*;
	public MultiplyElements getMultiplyAccess() {
		return pMultiply;
	}
	
	public ParserRule getMultiplyRule() {
		return getMultiplyAccess().getRule();
	}
	
	//AtomicNumber:
	//	ActualNumbers | NameAttribute;
	public AtomicNumberElements getAtomicNumberAccess() {
		return pAtomicNumber;
	}
	
	public ParserRule getAtomicNumberRule() {
		return getAtomicNumberAccess().getRule();
	}
	
	//ActualNumbers:
	//	FloatNum | IntNum;
	public ActualNumbersElements getActualNumbersAccess() {
		return pActualNumbers;
	}
	
	public ParserRule getActualNumbersRule() {
		return getActualNumbersAccess().getRule();
	}
	
	//NameAttribute:
	//	target=Target attribute=[Attribute];
	public NameAttributeElements getNameAttributeAccess() {
		return pNameAttribute;
	}
	
	public ParserRule getNameAttributeRule() {
		return getNameAttributeAccess().getRule();
	}
	
	//IntNum:
	//	value=INT;
	public IntNumElements getIntNumAccess() {
		return pIntNum;
	}
	
	public ParserRule getIntNumRule() {
		return getIntNumAccess().getRule();
	}
	
	//FloatNum:
	//	i=INT '.' decimal=INT;
	public FloatNumElements getFloatNumAccess() {
		return pFloatNum;
	}
	
	public ParserRule getFloatNumRule() {
		return getFloatNumAccess().getRule();
	}
	
	//Target:
	//	'User' | 'Enemy';
	public TargetElements getTargetAccess() {
		return pTarget;
	}
	
	public ParserRule getTargetRule() {
		return getTargetAccess().getRule();
	}
	
	//LegalType:
	//	'Float' | 'Integer';
	public LegalTypeElements getLegalTypeAccess() {
		return pLegalType;
	}
	
	public ParserRule getLegalTypeRule() {
		return getLegalTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
