/*
 * generated by Xtext 2.21.0
 */
package smitey.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import smitey.rpgindividual.ui.internal.RpgindividualActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RpgindividualExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RpgindividualActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RpgindividualActivator activator = RpgindividualActivator.getInstance();
		return activator != null ? activator.getInjector(RpgindividualActivator.SMITEY_RPGINDIVIDUAL) : null;
	}

}
