/*
 * generated by Xtext 2.21.0
 */
package smitey;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RpgindividualStandaloneSetup extends RpgindividualStandaloneSetupGenerated {

	public static void doSetup() {
		new RpgindividualStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
