/*
 * generated by Xtext 2.21.0
 */
package smitey.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import smitey.rpgindividual.ui.internal.RpgindividualActivator;

public class RpgindividualUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RpgindividualActivator.getInstance().getInjector("smitey.Rpgindividual");
	}

}
