/*
 * generated by Xtext 2.21.0
 */
package smitey.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRpgindividualScopeProvider extends DelegatingScopeProvider {
}
