/*
 * generated by Xtext 2.21.0
 */
package smitey.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import smitey.rpgindividual.SystemRPG
import org.eclipse.emf.ecore.EObject
import smitey.rpgindividual.Entity
import smitey.rpgindividual.Entities
import smitey.rpgindividual.Move

@ExtendWith(InjectionExtension)
@InjectWith(RpgindividualInjectorProvider)
class RpgindividualParsingTest {
	
	// Locations | Relations | Moves | Entities | Teams | Death | Attributes | Effects
	
	@Inject
	ParseHelper<SystemRPG> parseHelper
	
	@Test
	def void T00_loadModel() {

		val result = parseHelper.parse('''
			game TestGame
			
			location Test opponents TestTeamB
			
			relations
				type one
					zero < one < two
			
			attributes
				attribute testAttributeOne is Integer
				attribute testAttributeTwo is Integer
				
			death when User testAttributeOne <= 0
			
			effects
			    effect TestEffect 
			    if User testAttributeTwo > 0 then Enemy testAttributeOne is User testAttributeOne-1
			    
			moves
				move testMove type one
					attribute testAttributeTwo is Integer
					effect TestEffect
			
			entities
				entity TestEntityOne type one
					attribute testAttributeOne is 5
					move testMove()
				entity TestEntityOne type one
					attribute testAttributeOne is 5
					move testMove()
					
			teams
				team TestTeamA
					members TestEntityOne
				team TestTeamB
					members TestEntityTwo
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void T01_testDeclarationSize() {
		val result = parseHelper.parse('''
			game TestGame
			
			location Test opponents TestTeamB
			
			relations
				type one
					zero < one < two
			
			attributes
				attribute testAttributeOne is Integer
				attribute testAttributeTwo is Integer
				
			death when User testAttributeOne <= 0
			
			effects
			    effect TestEffect 
			    if User testAttributeTwo > 0 then Enemy testAttributeOne is User testAttributeOne-1
			    
			moves
				move testMove type one
					attribute testAttributeTwo is Integer
					effect TestEffect
			
			entities
				entity TestEntityOne type one
					attribute testAttributeOne is 5
					move testMove()
				entity TestEntityOne type one
					attribute testAttributeOne is 5
					move testMove()
					
			teams
				team TestTeamA
					members TestEntityOne
				team TestTeamB
					members TestEntityTwo
		''')
		Assertions.assertEquals(result.declarations.size(), 8)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	 
	@Test
	def void T02_testParseEntities() {
		val result = parseHelper.parse('''
			game TestGame
			
			location Test opponents TestTeamB
			
			relations
				type one
					zero < one < two
			
			attributes
				attribute testAttributeOne is Integer
				attribute testAttributeTwo is Integer
				
			death when User testAttributeOne <= 0
			
			effects
			    effect TestEffect 
			    if User testAttributeTwo > 0 then Enemy testAttributeOne is User testAttributeOne-1
			    
			moves
				move testMove type one
					attribute testAttributeTwo is Integer
					effect TestEffect
			
			entities
				entity TestEntityOne type one
					attribute testAttributeOne is 5
					move testMove()
				entity TestEntityOne type one
					attribute testAttributeOne is 5
					move testMove()
					
			teams
				team TestTeamA
					members TestEntityOne
				team TestTeamB
					members TestEntityTwo
		''')
		Assertions.assertTrue(result.declarations.get(6) instanceof Entities)
		Assertions.assertTrue(result.declarations.get(6).eContents.size == 2)
		for(EObject e : result.declarations.get(6).eContents) {
			val temp = e as Entity
			Assertions.assertTrue(temp.name == "TestEntityOne" || temp.name == "TestEntityTwo")
			Assertions.assertTrue(temp.EMoves.move.size > 0)
			Assertions.assertTrue(temp.EMoves.move.get(0).moveName instanceof Move)
			Assertions.assertTrue(temp.EMoves.move.get(0).moveName.name == "testMove")
		}
		
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
