/*
 * generated by Xtext 2.21.0
 */
package smitey.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RpgindividualUiModule extends AbstractRpgindividualUiModule {

	public RpgindividualUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
