/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual.impl;

import org.eclipse.emf.ecore.EClass;

import smitey.rpgindividual.ActualNumbers;
import smitey.rpgindividual.RpgindividualPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Actual Numbers</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ActualNumbersImpl extends AtomicNumberImpl implements ActualNumbers
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActualNumbersImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RpgindividualPackage.Literals.ACTUAL_NUMBERS;
  }

} //ActualNumbersImpl
