/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual.impl;

import org.eclipse.emf.ecore.EClass;

import smitey.rpgindividual.RpgindividualPackage;
import smitey.rpgindividual.Smaller;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Smaller</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SmallerImpl extends ComparatorImpl implements Smaller
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SmallerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RpgindividualPackage.Literals.SMALLER;
  }

} //SmallerImpl
