/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import smitey.rpgindividual.FloatNum;
import smitey.rpgindividual.RpgindividualPackage;
import smitey.rpgindividual.Type;
import smitey.rpgindividual.TypeExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.impl.TypeExpressionImpl#getRelationStrong <em>Relation Strong</em>}</li>
 *   <li>{@link smitey.rpgindividual.impl.TypeExpressionImpl#getStrong <em>Strong</em>}</li>
 *   <li>{@link smitey.rpgindividual.impl.TypeExpressionImpl#getStrong2 <em>Strong2</em>}</li>
 *   <li>{@link smitey.rpgindividual.impl.TypeExpressionImpl#getRelationWeak <em>Relation Weak</em>}</li>
 *   <li>{@link smitey.rpgindividual.impl.TypeExpressionImpl#getWeak <em>Weak</em>}</li>
 *   <li>{@link smitey.rpgindividual.impl.TypeExpressionImpl#getWeak2 <em>Weak2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TypeExpressionImpl extends MinimalEObjectImpl.Container implements TypeExpression
{
  /**
   * The cached value of the '{@link #getRelationStrong() <em>Relation Strong</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationStrong()
   * @generated
   * @ordered
   */
  protected FloatNum relationStrong;

  /**
   * The cached value of the '{@link #getStrong() <em>Strong</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrong()
   * @generated
   * @ordered
   */
  protected Type strong;

  /**
   * The cached value of the '{@link #getStrong2() <em>Strong2</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrong2()
   * @generated
   * @ordered
   */
  protected EList<Type> strong2;

  /**
   * The cached value of the '{@link #getRelationWeak() <em>Relation Weak</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationWeak()
   * @generated
   * @ordered
   */
  protected FloatNum relationWeak;

  /**
   * The cached value of the '{@link #getWeak() <em>Weak</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeak()
   * @generated
   * @ordered
   */
  protected Type weak;

  /**
   * The cached value of the '{@link #getWeak2() <em>Weak2</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeak2()
   * @generated
   * @ordered
   */
  protected EList<Type> weak2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RpgindividualPackage.Literals.TYPE_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FloatNum getRelationStrong()
  {
    return relationStrong;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRelationStrong(FloatNum newRelationStrong, NotificationChain msgs)
  {
    FloatNum oldRelationStrong = relationStrong;
    relationStrong = newRelationStrong;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG, oldRelationStrong, newRelationStrong);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelationStrong(FloatNum newRelationStrong)
  {
    if (newRelationStrong != relationStrong)
    {
      NotificationChain msgs = null;
      if (relationStrong != null)
        msgs = ((InternalEObject)relationStrong).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG, null, msgs);
      if (newRelationStrong != null)
        msgs = ((InternalEObject)newRelationStrong).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG, null, msgs);
      msgs = basicSetRelationStrong(newRelationStrong, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG, newRelationStrong, newRelationStrong));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type getStrong()
  {
    if (strong != null && strong.eIsProxy())
    {
      InternalEObject oldStrong = (InternalEObject)strong;
      strong = (Type)eResolveProxy(oldStrong);
      if (strong != oldStrong)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RpgindividualPackage.TYPE_EXPRESSION__STRONG, oldStrong, strong));
      }
    }
    return strong;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type basicGetStrong()
  {
    return strong;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStrong(Type newStrong)
  {
    Type oldStrong = strong;
    strong = newStrong;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RpgindividualPackage.TYPE_EXPRESSION__STRONG, oldStrong, strong));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Type> getStrong2()
  {
    if (strong2 == null)
    {
      strong2 = new EObjectResolvingEList<Type>(Type.class, this, RpgindividualPackage.TYPE_EXPRESSION__STRONG2);
    }
    return strong2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FloatNum getRelationWeak()
  {
    return relationWeak;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRelationWeak(FloatNum newRelationWeak, NotificationChain msgs)
  {
    FloatNum oldRelationWeak = relationWeak;
    relationWeak = newRelationWeak;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK, oldRelationWeak, newRelationWeak);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelationWeak(FloatNum newRelationWeak)
  {
    if (newRelationWeak != relationWeak)
    {
      NotificationChain msgs = null;
      if (relationWeak != null)
        msgs = ((InternalEObject)relationWeak).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK, null, msgs);
      if (newRelationWeak != null)
        msgs = ((InternalEObject)newRelationWeak).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK, null, msgs);
      msgs = basicSetRelationWeak(newRelationWeak, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK, newRelationWeak, newRelationWeak));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type getWeak()
  {
    if (weak != null && weak.eIsProxy())
    {
      InternalEObject oldWeak = (InternalEObject)weak;
      weak = (Type)eResolveProxy(oldWeak);
      if (weak != oldWeak)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RpgindividualPackage.TYPE_EXPRESSION__WEAK, oldWeak, weak));
      }
    }
    return weak;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type basicGetWeak()
  {
    return weak;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWeak(Type newWeak)
  {
    Type oldWeak = weak;
    weak = newWeak;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RpgindividualPackage.TYPE_EXPRESSION__WEAK, oldWeak, weak));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Type> getWeak2()
  {
    if (weak2 == null)
    {
      weak2 = new EObjectResolvingEList<Type>(Type.class, this, RpgindividualPackage.TYPE_EXPRESSION__WEAK2);
    }
    return weak2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG:
        return basicSetRelationStrong(null, msgs);
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK:
        return basicSetRelationWeak(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG:
        return getRelationStrong();
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG:
        if (resolve) return getStrong();
        return basicGetStrong();
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG2:
        return getStrong2();
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK:
        return getRelationWeak();
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK:
        if (resolve) return getWeak();
        return basicGetWeak();
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK2:
        return getWeak2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG:
        setRelationStrong((FloatNum)newValue);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG:
        setStrong((Type)newValue);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG2:
        getStrong2().clear();
        getStrong2().addAll((Collection<? extends Type>)newValue);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK:
        setRelationWeak((FloatNum)newValue);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK:
        setWeak((Type)newValue);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK2:
        getWeak2().clear();
        getWeak2().addAll((Collection<? extends Type>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG:
        setRelationStrong((FloatNum)null);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG:
        setStrong((Type)null);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG2:
        getStrong2().clear();
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK:
        setRelationWeak((FloatNum)null);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK:
        setWeak((Type)null);
        return;
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK2:
        getWeak2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_STRONG:
        return relationStrong != null;
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG:
        return strong != null;
      case RpgindividualPackage.TYPE_EXPRESSION__STRONG2:
        return strong2 != null && !strong2.isEmpty();
      case RpgindividualPackage.TYPE_EXPRESSION__RELATION_WEAK:
        return relationWeak != null;
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK:
        return weak != null;
      case RpgindividualPackage.TYPE_EXPRESSION__WEAK2:
        return weak2 != null && !weak2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TypeExpressionImpl
